name: mycalorie
description: تطبيق حساب السعرات الحرارية وتتبع شرب الماء
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  device_preview: ^1.2.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
